import React, { useRef } from 'react';
import { useInTextFootnoteNumbering } from '../../hooks/useInTextFootnoteNumbering';
import { useCitationData } from '../../hooks/useCitationData';
import { FootnoteList } from '../../components/FootnoteList';

const footnotesConfig = [
    { id: 'fn1', doi: '10.64898/2026.03.03.709355' },  // Kosonocky et al 2026
    { id: 'fn2', doi: '10.1101/2023.12.14.571651' },   // Wang et al 2023b
    { id: 'fn3', doi: '10.1101/2025.11.20.689494' },   // Stärk et al 2025
];

export const post = {
  id: '2026-03-06-glu-lys',
  title: 'Glutamate- and lysine-rich designs can fail due to expression failures resulting from adenosine-rich sequences',
  date: '2026-03-06',
  category: 'Bio/ML',
  content: (() => {
    const ContentComponent = () => {
      const contentRef = useRef(null);
      const idToNumberMap = useInTextFootnoteNumbering(contentRef);
      const { citationsData, isLoading, error } = useCitationData(footnotesConfig, { template: 'apa' });

      return (
        <div className="content-container" ref={contentRef}>
          <p><strong>Designs generated by inverse folding that are rich in glutamates and lysines can fail due to expression failures resulting from adenosine-rich sequences</strong><sup className="footnote-ref">[<a href="#fn1" id="fnref1"></a>]</sup>. In the Bits in Bio 2026 competition, these were overrepresented by designs from ProteinMPNN, particularly those rich in alpha helices. The authors' diagnosis, which also showed that nearly all tested non-MPNN designs expressed, is worth reading in full.

          <img src="/assets/post_images/2026_03_06/2026_03_06_glu_A.png" alt="Figure from Kosonocky et al 2026" width="300" style={{ display: 'block', marginLeft: 'auto', marginRight: 'auto', height: 'auto' }} />
          <p style={{ textAlign: 'center', fontStyle: 'italic' }}>Figure from Kosonocky et al 2026<sup className="footnote-ref">[<a href="#fn1" id="fnref1"></a>]</sup></p>

          High lysine and glutamate content was observed in ProteinMPNN outputs in previous studies<sup className="footnote-ref">[<a href="#fn2" id="fnref2"></a>]</sup> and has been replicated in multiple labs<sup className="footnote-ref">[<a href="#fn3" id="fnref3"></a>]</sup>.</p>

          <img src="/assets/post_images/2026_03_06/2026_03_06_glu_B.png" alt="Figure 4B from Wang et al 2023b" width="300" style={{ display: 'block', marginLeft: 'auto', marginRight: 'auto', height: 'auto' }} />
          <p style={{ textAlign: 'center', fontStyle: 'italic' }}>Figure from Wang et al 2023<sup className="footnote-ref">[<a href="#fn2" id="fnref2"></a>]</sup></p>
          <img src="/assets/post_images/2026_03_06/2026_03_06_glu_C.png" alt="Figure from Stärk et al 2025" width="700" style={{ display: 'block', marginLeft: 'auto', marginRight: 'auto', height: 'auto' }} />
          <p style={{ textAlign: 'center', fontStyle: 'italic' }}>Figure from Stärk et al 2025<sup className="footnote-ref">[<a href="#fn3" id="fnref3"></a>]</sup></p>

          <FootnoteList
            citationsData={citationsData}
            idToNumberMap={idToNumberMap}
            isLoading={isLoading}
            error={error}
          />
        </div>
      );
    };
    return <ContentComponent />;
  })(),
};
